albums/urls.py
from django.conf.urls import patterns, url
from albums.views import AlbumListView, AlbumDetailView


urlpatterns = patterns('',
    url(r'^albums/$', AlbumListView.as_view(), name='album_list'),
    url(r'^albums/(?P<artist>[\w\-]+)/$', AlbumListView.as_view(), name='album_list'),
    url(r'^albums/detail/(?P<id>[\w\-]+)/$', AlbumDetailView.as_view(), name='album_detail'),
)

artists/urls.py
from django.conf.urls import patterns, url
from artists.views import ArtistDetailView

urlpatterns = patterns('',
    url(r'^artists/(?P<pk>[\d]+)', ArtistDetailView.as_view()),
)

sfotipy/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sfotipy.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    (r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'', include('userprofiles.urls')),
    url(r'', include('albums.urls')),
    url(r'', include('artists.urls')),
    url(r'', include('tracks.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, }),
    )

tracks/urls.py
from django.conf.urls import patterns, url
from tracks.views import track_view

urlpatterns = patterns('',
    url(r'^tracks/(?P<title>[\w\-\W]+)/', 'track_view',
        name='track_view'),
)

userprofiles/urls.py
from django.conf.urls import patterns, url
from userprofiles.views import LoginView, ProfileView, PerfilRedirectView
#from django.views.generic import TemplateView


urlpatterns = patterns('',
    url(r'^login/$', LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^profil/$', ProfileView.as_view(), name='profile'),
    url(r'^perfil/$', PerfilRedirectView.as_view(), name='perfil'),
)

albums/models.py
from django.db import models

from artists.models import Artist


class Album(models.Model):
    title = models.CharField(max_length=255)
    cover = models.ImageField(upload_to='albums')
    artist = models.ForeignKey(Artist)

    def __str__(self):
        return self.title

artists/models.py
from django.db import models


class Artist(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255, blank=True)
    biography = models.TextField(blank=True)
    favorite_songs = models.ManyToManyField('tracks.Track', blank=True,
                                            related_name='is_favotite_of')

    def __str__(self):
        return self.first_name

tracks/models.py
from django.db import models

from albums.models import Album
from artists.models import Artist


class Track(models.Model):
    title = models.CharField(max_length=255)
    order = models.PositiveIntegerField()
    track_file = models.FileField(upload_to='tracks')
    album = models.ForeignKey(Album)
    artist = models.ForeignKey(Artist)

    def get_absolute_url(self):
        return '/tracks/%s/' % self.title

    def player(self):
        return """
        <audio controls>
            <source src="%s" type="audio/mpeg">
            Your browser no support the audio tag
        </audio>
        """ % self.track_file.url

    player.allow_tags = True
    player.admin_order_field = 'title'

    def __str__(self):
        return self.title

userprofiles/models.py
from django.db import models

from django.contrib.auth.models import User
from tracks.models import Track


class UserProfile(models.Model):
    avatar = models.ImageField(upload_to='avatars')
    user = models.OneToOneField(User)

    def __str__(self):
        return self.user.username


class UserTrack(models.Model):
    count = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User)
    track = models.ForeignKey(Track)

userprofiles/forms.py
#-*- coding:utf-8 -*-
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreationEmailForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username', 'email')


class EmailAuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(label='password', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        self.user_cache = None
        super(EmailAuthenticationForm, self).__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        self.user_cache = authenticate(email=email, password=password)

        if self.user_cache is None:
            raise forms.ValidationError('Usuario o Contraseña, incorrectos')
        elif not self.user_cache.is_active:
            raise forms.ValidationError('Usuario inactivo')

        return self.cleaned_data

    def get_user(self):
        return self.user_cache

albums/views.py
from albums.models import Album
from django.views.generic import ListView, DetailView
#from django.shortcuts import render


class AlbumListView(ListView):
    model = Album
    template_name = 'album_list.html'
    paginate_by = 25

    def get_queryset(self):
        if self.kwargs.get('artist'):
            queryset = self.model.objects.filter(artist__first_name__contains=self.kwargs['artist'])
        else:
            queryset = super(AlbumListView, self).get_queryset()

        return queryset


class AlbumDetailView(DetailView):
    model = Album
    template_name = 'album_detail.html'

artists/views.py
from .models import Artist
from django.views.generic.detail import DetailView
#from django.shortcuts import render


class ArtistDetailView(DetailView):
    model = Artist
    context_object_name = 'artist'

    def get_template_names(self):
        return 'artist.html'

tracks/views.py
#import json
from django.shortcuts import render, get_object_or_404
#from django.http import HttpResponse

from .models import Track

#@login_required
def track_view(request, title):
    #import ipdb; ipdb.set_trace()
    track = get_object_or_404(Track, title=title)
    bio = track.artist.biography

    data = {
        'title': track.title,
        'order': track.order,
        'album': track.album,
        'artist': {
            'name': track.artist.first_name,
            'bio': bio,
        }
    }

    #json_data = json.dumps(data)
    #return HttpResponse(json_data, content_type='application/json')
    return render(request, 'track.html', {'track': track, 'bio': bio})

userprofiles/views.py
from django.views.generic import TemplateView, RedirectView
from django.http import HttpResponse
#from django.shortcuts import render
#from django.contrib.auth import login

#from .forms import UserCreationEmailForm, EmailAuthenticationForm


class LoginView (TemplateView):
    template_name = 'login.html'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        is_auth = False
        name = None

        if self.request.user.is_authenticated():
            is_auth = True
            name = self.request.user.username

        data = {
            'is_auth': is_auth,
            'name': name,
        }

        context.update(data)
        return context


class ProfileView(TemplateView):
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)

        if self.request.user.is_authenticated():
            context.update({'userprofile': self.get_userprofile()})

        return context

    def get_userprofile(self):
        return self.request.user.userprofile


class PerfilRedirectView(RedirectView):
    pattern_name = 'profile'

albums/templates/album_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ album.title }}</h1>
    <div class="row">
        <div class="col-md-6">
            <figure>
                <img src="/media/{{ album.cover }}" alt="{{ album.title }}" width="350" />
                <figcaption>{{ album.artist.first_name }}</figcaption>
            </figure>
        </div>
        <div class="col-md-6">
            <ul>
                {% for track in album.track_set.all %}
                    <li style="list-style-type: none;">{{ track }}</li>
                {% empty %}
                    <div>No hay tracks todavía.</div>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

albums/templates/album_list.html
{% extends 'base.html' %}

{% block head_title %}Lista de Albumnes{% endblock %}

{% block content %}
<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <h1>Álbumes</h1>
    <div>Page: {{ page }}</div>
      {% for album in object_list %}
      <div class="col-md-4">
        <a href="{{ album.artist.first_name }}">
        <figure>
          <img src="/media/{{ album.cover }}" alt="{{ album.title }}" width="250" height="250"/>
          <figcaption>{{ album.title }}</figcaption>
          <figcaption>By {{ album.artist.first_name }} {{ album.artist.last_name }}</figcaption>
        </figure>
        </a>
      </div>
      {% empty %}
          <div>No hay álbumes todavía.</div>
      {% endfor %}
  </div>
</div>
{% endblock %}

albums/templates/track_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Top Tracks!!</h1>
    <div>
        <ul>
            {% for track in object_list %}
                <li>{{ track.title }}: {{ track.listen }}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

artists/templates/artist.html
{{artist.first_name}} {{artist.last_name}}

tracks/templates/track.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Track {{titulo}}</title>
</head>
<body>
    <section>
        <ul>
            {% for track in tracks %}
            <li>
                {% if track == selected_track %} ----- 
                {% else %}
                <a href="{{track.get_absolute_url}}"> {{track.title}} </a>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        <p>
            Título: {{track.title}}
        </p>
        <p>
            Pista: {{track.order}}
        </p>
        <p>
            Archivo: {{track.trackfield}}
        </p>
        <p>
            Album: {{track.album}}
        </p>
        <p>
            Artista: {{track.artist}}
        </p>
        <p>
            Biografía: {{bio}}
        </p>
    </section>
    
</body>
</html>

userprofiles/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block head_title %}{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
        {% block head_css %}{% endblock %}
        {% block head_javascript %}{% endblock %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. 
            Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your 
            experience.</p>
        <![endif]-->
    {% block navbar %}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" 
          data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">GymSXXI</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form" method="post">
          {% csrf_token %}
            <div class="form-group">
          {% if is_auth %}
              <button type="submit" class="btn btn-success">{{ name }}</button>
            </div>
            <button type="submit" class="btn btn-success">Salir</button>
          </form>
           
          {% else %}
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Iniciar</button>
          </form>
          {% endif %}
        </div><!--/.navbar-collapse -->
      </div>
    </div>
    {% endblock %}

    {% block content %}{% endblock %}

      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->        
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || 
            document.write('<script src="static/js/vendor/jquery-1.11.0.min.js"><\/script>')
            </script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

        {% block footer_javascript %}{% endblock %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>

userprofiles/templates/login.html
{% extends "base.html" %}
{% load i18n %}
{% load l10n %}
{% load tz %}

{% block head_title %}TaskBuster Django Tutorial{% endblock %}

{% block content %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>{% trans '¡Bienvenidos a TaskBuster!' %}</h1>
        <p>{% if is_auth %}{{ name }}{% else %}No hay nadie autenticado{% endif %}
        <p>{% blocktrans %}TaskBuster es un simple gestor de tareas que te ayudará a administrar tu día a día. </br> Puedes crear listas de cosas pendientes, tareas periódicas y ¡mucho mas! </br></br> Si quieres aprender como se ha creado, o crearlo ¡tu mismo!, visita la página www.django-tutorial.com{% endblocktrans %}</p>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2 id="locale-date">{{today}}</h2>
          <p>{% trans "Esta es la hora usando tu información local." %}</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2 id="non-locale-date">{{today|unlocalize}}</h2>
          <p>{% trans "Este es el formato por defecto." %}</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>{% trans "Zonas Horarias" %}</h2>
          <p>Madrid: <span id="time-tz">{{now|time:"H:i"}}</span></p>
          <p>UTC: <span id="time-utc">{{now|utc|time:"H:i"}}</span></p>
          <p>New York: <span id="time-ny">
            {{now|timezone:"America/New_York"|time:"H:i"}}</span></p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
{% endblock %}

userprofiles/templates/profile.html
{% extends "base.html" %}
{% load i18n %}
{% load l10n %}
{% load tz %}

{% block head_title %}TaskBuster Django Tutorial{% endblock %}

{% block content %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>{% trans 'Perfil de Usuario' %}</h1>
        <p>{% if is_auth %}{{ name }}{% else %}No hay nadie autenticado{% endif %}
        <p>{% blocktrans %}TaskBuster es un simple gestor de tareas que te ayudará a administrar tu día a día. </br> Puedes crear listas de cosas pendientes, tareas periódicas y ¡mucho mas! </br></br> Si quieres aprender como se ha creado, o crearlo ¡tu mismo!, visita la página www.django-tutorial.com{% endblocktrans %}</p>
        <p><a class="btn btn-primary btn-lg" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2 id="locale-date">{{today}}</h2>
          <p>{% trans "Esta es la hora usando tu información local." %}</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2 id="non-locale-date">{{today|unlocalize}}</h2>
          <p>{% trans "Este es el formato por defecto." %}</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-md-4">
          <h2>{% trans "Zonas Horarias" %}</h2>
          <p>Madrid: <span id="time-tz">{{now|time:"H:i"}}</span></p>
          <p>UTC: <span id="time-utc">{{now|utc|time:"H:i"}}</span></p>
          <p>New York: <span id="time-ny">
            {{now|timezone:"America/New_York"|time:"H:i"}}</span></p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>
{% endblock %}

userprofiles/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<section>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Enviar">
    </form>
</section>
    
</body>
</html>

userprofiles/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<body>
    <section>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Enviar">
        </form>
    </section>
</body>
</html>